version: '2'
services:
  webapp:
    build: .
    volumes:
      - .:/webapp
    ports:
      - 3000:3000
    container_name: webapp
    links:
      - db
    command: bash -c "sh /webapp/scripts/startup.sh && sh install_bootstrap_4.0.sh"
    env_file: .env
  db:
    image: postgres
    container_name: db
    env_file: .env
